### ISSUE TITLE
UML sequence styling issue

### ISSUE THREAD

**Issue by Redsandro** [benweet/stackedit#1021]
The boxes are transparent, causing problems:

![image](https://cloud.githubusercontent.com/assets/1702193/18796781/1e9746d8-81cb-11e6-826b-6db669327811.png)

As seen on: Chrome 55.0.2859.0 dev (64-bit)

**Comment by Redsandro** [comment]
__Work-around__

Manually add:

```css
.sequence-diagram [stroke="#000000"], .flow-chart [stroke="#000000"] {
    fill: #fff;
}
```
