### ISSUE TITLE
The input (p) is transcoded

### ISSUE THREAD

**Issue by jackercc** [benweet/stackedit#1660]
When input '(p)', the result is not i want get.

![image](https://user-images.githubusercontent.com/19639723/86429215-799b1b00-bd21-11ea-929a-dbc92eab4ab8.png)

**Comment by jackercc** [comment]
i can use span to avoid this like (<span>p</span>) , but why it happen?

**Comment by jeremyredhead** [comment]
It looks like `(p)` is one of the "typographic replacements" performed used by stackedit's markdown library, [markdown-it](https://markdown-it.github.io/)
It is similar to conversion of `(c)` to ©, `(TM)` to ™, etc.
It could be disabled in File Properties (in the top-right menu), by adding something like this:
```yaml
extensions:
  markdown:
    # Disable "typographic replacements" such as (c), (tm), (p)
    typographer: false
```
