### ISSUE TITLE
How to reduce the interline space under the item of a list

### ISSUE THREAD

**Issue by gilgaTheDev** [benweet/stackedit#1855]
I tried this in Settings > Custom Settings, but it doesn't change anything:

```
wkhtmltopdf:
  ul, ol:
    margin: 0
    padding: 0

  li:
    margin-bottom: 0.2em  
    line-height: 1.2 
```  

Thanks!
