### ISSUE TITLE
TOC is rendered as `TOC` in Gist

### ISSUE THREAD

**Issue by weppos** [benweet/stackedit#647]
When you use the `[TOC]` macro and you publish the document to a Gist, the macro is not expanded as in the editor preview, but instead the string `[TOC]` is published.

**Comment by abhimanyusharma003** [comment]
:+1:

**Comment by TheKnightCoder** [comment]
Any fix for this? or walkaround

**Comment by hankyusa** [comment]
I've put both `[toc]` and `[TOC]` all over the document with no joy. I have the following in my settings. 
```yaml
pandoc:
  highlightStyle: kate
  toc: true
  tocDepth: 3
```
Any other ideas?
