### ISSUE TITLE
base.css Uses justify by default

### ISSUE THREAD

**Issue by bibhas2** [benweet/stackedit#769]
When I export the document using template, paragraphs are using ``justify``. This not only looks bad in many cases, it also does not reflect what I am authoring (during authoring left align is used). The root cause is ``base.css`` using:

```css
.container {
  margin-bottom: 180px;
  text-align: justify;
}
```
