### ISSUE TITLE
Document scrolls rapidly back and forth during typing

### ISSUE THREAD

**Issue by Tigt** [benweet/stackedit#851]
On Firefox for OS X, typing in the editor can cause the scroll position to rapidly flicker up and back down on every other keystroke or so. I disabled scroll syncing, but nothing changed. Mucking around in the devtools reveals some rather hellacious style recalc occuring, described as being caused by CSS animations and transitions.

I have a screen recording if that helps, but I'm not sure where to upload it.

**Comment by Tigt** [comment]
I added the following rule during the issue:

```css
*, :before, :after {
  transition: none !important;
  animation: none !important;
}
```

But the effect remains.

Some more investigation reveals it doesn't happen as long as the last heading is still onscreen.
